version: '3'

services:
  nginx:
    container_name: test_nginx
    build:
      context: ./docker/nginx/
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
    depends_on:
      - php

  php:
    container_name: test_php
    build:
      context: ./docker/php/
    volumes:
      - ./src:/var/www/vhosts/test/:cached
      - ./docker/php/www.conf:/etc/php-fpm.d/www.conf:cached
      - ./docker/php/php.ini:/etc/php.ini:cached

  db:
    image: mysql:8.0
    container_name: test_db
    hostname: mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-time-zone=Asia/Tokyo
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: test_pma
    hostname: phpmyadmin
    depends_on:
      - db
    ports:
      - "8888:80"
